version: "3.9"
services:
    streamlit:
        image: manchester-transport-dashboard
        build:
          context: .
          dockerfile: Dockerfile
          args:
            DASHBOARD_BUILD_VERSION: docker_compose_version
        env_file:
          - .streamlit/secrets.toml
        ports:
          - '8501':'8501'