name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    
    - name: Log in to Docker Hub
      uses: docker/login-action
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Log in to the Container registry
      uses: docker/login-action
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action
      with:
        images: |
          nickmanc/manchester-transport-dashboard
          ghcr.io/${{ github.repository }}
        flavor: latest=true
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}},value=0.0.{{github.run_number}}

    - name: Build and push Docker images
      uses: docker/build-push-action
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}